import { generateAuthenticUtr } from '../services/fraudEngine';

export const DEMO_USERS = {
  merchant: {
    id: 1,
    name: 'Vikram Sharma',
    email: 'merchant@upishield.demo',
    role: 'merchant',
    business_name: 'Apex Supermart & Electronics',
    merchant_vpa: 'apex.retail@okhdfcbank',
    terminal_id: 'POS-DEL-9821',
    phone: '+91 98765 43210',
    avatar: 'VS',
    apiKey: 'sk_live_upi_98a7f230e9d145c8',
    webhookUrl: 'https://api.apexmart.in/webhooks/upi-shield',
  },
  admin: {
    id: 2,
    name: 'Ananya Roy',
    email: 'admin@upishield.demo',
    role: 'admin',
    business_name: 'NPCI & Banking Fraud Risk Operations',
    merchant_vpa: 'compliance@npci.gov.in',
    terminal_id: 'HQ-CYBER-001',
    phone: '+91 99887 76655',
    avatar: 'AR',
    apiKey: 'sk_admin_root_44b2091ea0398',
    webhookUrl: 'https://security.npci.org/alerts/stream',
  },
};

export const INITIAL_FRAUD_RULES = [
  {
    id: 1,
    rule_code: 'RULE_JULIAN_SYNTAX',
    rule_name: '12-Digit UTR Julian Calendar Validation',
    description: 'Enforces Indian Banking standards: Year digit + Julian Day (001–366). Flags fake 10-digit APK generators.',
    weight: 35,
    is_enabled: true,
    threshold_value: '12 Digits, Day <= 366',
  },
  {
    id: 2,
    rule_code: 'RULE_REPLAY_DUP',
    rule_name: 'Cross-Merchant Replay Attack Detection',
    description: 'Checks global ledger for recycled UTR numbers previously redeemed at any counter.',
    weight: 45,
    is_enabled: true,
    threshold_value: '0 Permitted Duplicates',
  },
  {
    id: 3,
    rule_code: 'RULE_VPA_INTEGRITY',
    rule_name: 'Beneficiary Receiver VPA Verification',
    description: 'Compares extracted payee UPI handle against the store’s authorized bank VPA.',
    weight: 30,
    is_enabled: true,
    threshold_value: 'Strict Match Required',
  },
  {
    id: 4,
    rule_code: 'RULE_BLACKLIST_CHECK',
    rule_name: 'National Fraud Registry VPA Blacklist',
    description: 'Instant match against reported mule accounts and cybercrime database.',
    weight: 50,
    is_enabled: true,
    threshold_value: 'Zero Tolerance Flag',
  },
  {
    id: 5,
    rule_code: 'RULE_TIME_DELTA',
    rule_name: 'Screenshot Temporal Delta Anomaly',
    description: 'Calculates latency between receipt timestamp and checkout verification time.',
    weight: 20,
    is_enabled: true,
    threshold_value: '< 15 Minutes Delta',
  },
];

export const INITIAL_BLACKLIST_VPAS = [
  {
    id: 1,
    vpa: 'scammer.loot@ybl',
    reason: 'Reported in 14 fake PhonePe spoof complaints across Delhi-NCR',
    reported_by: 'Cyber Cell East',
    added_at: '2026-10-02 11:20:00',
    risk: 'CRITICAL',
  },
  {
    id: 2,
    vpa: 'quickcash.refund@axl',
    reason: 'Known spoof APK default demo address used in phishing attacks',
    reported_by: 'State Bank Fraud Unit',
    added_at: '2026-09-28 14:45:00',
    risk: 'CRITICAL',
  },
  {
    id: 3,
    vpa: 'lottery.winner88@paytm',
    reason: 'Advance payment fraud mule account',
    reported_by: 'Apex Supermart',
    added_at: '2026-10-05 09:15:00',
    risk: 'HIGH',
  },
  {
    id: 4,
    vpa: 'fastpay.agent99@okaxis',
    reason: 'Targeted QR code sticker swapping fraudster',
    reported_by: 'Mumbai Merchant Guild',
    added_at: '2026-10-06 16:30:00',
    risk: 'CRITICAL',
  },
];

export const INITIAL_TRANSACTIONS = [
  {
    id: 'TXN-9041',
    user_id: 1,
    utr_number: '628109482914',
    amount: 1450.00,
    sender_vpa: 'rohit.kumar@okicici',
    receiver_vpa: 'apex.retail@okhdfcbank',
    timestamp: '2026-10-07 15:32:14',
    verification_mode: 'manual',
    risk_score: 8,
    risk_level: 'LOW',
    verdict: 'VERIFIED GENUINE',
    status: 'verified',
    risk_factors: [
      { code: 'SYNTAX_OK', title: 'Valid 12-Digit Indian UTR', points: 0, severity: 'SAFE' },
      { code: 'JULIAN_OK', title: 'Julian Day 281 Verified', points: 0, severity: 'SAFE' },
    ],
    notes: 'In-store retail billing counter 1',
  },
  {
    id: 'TXN-9040',
    user_id: 1,
    utr_number: '9381029481',
    amount: 3500.00,
    sender_vpa: 'unknown.user@paytm',
    receiver_vpa: 'apex.retail@okhdfcbank',
    timestamp: '2026-10-07 14:18:02',
    verification_mode: 'ocr_screenshot',
    risk_score: 85,
    risk_level: 'HIGH',
    verdict: 'HIGH RISK FRAUD DETECTED',
    status: 'flagged',
    risk_factors: [
      { code: 'UTR_INVALID_LENGTH', title: 'Invalid UTR Length (10 Digits)', description: 'Known Fake Paytm APK generator artifact', points: 40, severity: 'HIGH' },
      { code: 'FONT_TAMPER', title: 'Non-Standard Font Rendering', description: 'OCR detected typographic mismatch with official app', points: 25, severity: 'HIGH' },
      { code: 'JULIAN_ERR', title: 'Fails Julian Calendar Algorithm', description: 'Cannot decode settlement day', points: 20, severity: 'HIGH' },
    ],
    notes: 'Suspicious customer fled when verification screen loaded',
  },
  {
    id: 'TXN-9039',
    user_id: 1,
    utr_number: '628109482914',
    amount: 1450.00,
    sender_vpa: 'different.person@ybl',
    receiver_vpa: 'apex.retail@okhdfcbank',
    timestamp: '2026-10-07 15:45:10',
    verification_mode: 'manual',
    risk_score: 90,
    risk_level: 'HIGH',
    verdict: 'REPLAY ATTACK CONFIRMED',
    status: 'rejected',
    risk_factors: [
      { code: 'REPLAY_ATTACK_DUPLICATE', title: 'Duplicate UTR Replay Attack', description: 'UTR previously verified at 15:32:14 today', points: 45, severity: 'CRITICAL' },
      { code: 'SENDER_ANOMALY', title: 'Sender VPA Swapped', points: 25, severity: 'HIGH' },
    ],
    notes: 'Recycled payment screenshot attempt intercepted',
  },
  {
    id: 'TXN-9038',
    user_id: 1,
    utr_number: '628145009182',
    amount: 620.00,
    sender_vpa: 'priya.sharma@oksbi',
    receiver_vpa: 'apex.retail@okhdfcbank',
    timestamp: '2026-10-07 13:50:22',
    verification_mode: 'manual',
    risk_score: 6,
    risk_level: 'LOW',
    verdict: 'VERIFIED GENUINE',
    status: 'verified',
    risk_factors: [
      { code: 'SYNTAX_OK', title: 'Standard 12-Digit UTR Verified', points: 0, severity: 'SAFE' },
    ],
    notes: 'Grocery aisle express lane',
  },
  {
    id: 'TXN-9037',
    user_id: 1,
    utr_number: '628188491023',
    amount: 8900.00,
    sender_vpa: 'scammer.loot@ybl',
    receiver_vpa: 'apex.retail@okhdfcbank',
    timestamp: '2026-10-07 12:15:40',
    verification_mode: 'manual',
    risk_score: 75,
    risk_level: 'HIGH',
    verdict: 'BLACKLISTED SENDER IDENTIFIED',
    status: 'flagged',
    risk_factors: [
      { code: 'BLACKLISTED_SENDER', title: 'National Fraud Blacklist Hit', description: 'Sender VPA in cybercrime database', points: 50, severity: 'CRITICAL' },
      { code: 'HIGH_VALUE_THRESHOLD', title: 'High-Value Threshold Warning', points: 15, severity: 'LOW' },
    ],
    notes: 'Electronics counter - hold merchandise',
  },
  {
    id: 'TXN-9036',
    user_id: 1,
    utr_number: '628099847120',
    amount: 2400.00,
    sender_vpa: 'amit.patel@okaxis',
    receiver_vpa: 'other.store@okaxis',
    timestamp: '2026-10-07 11:05:18',
    verification_mode: 'ocr_screenshot',
    risk_score: 45,
    risk_level: 'MEDIUM',
    verdict: 'RECEIVER VPA MISMATCH',
    status: 'disputed',
    risk_factors: [
      { code: 'VPA_MISMATCH', title: 'Receiver VPA Discrepancy', description: 'Receipt addressed to other.store@okaxis', points: 30, severity: 'HIGH' },
      { code: 'TIME_DELTA', title: 'Receipt Generated 42 Minutes Ago', points: 15, severity: 'LOW' },
    ],
    notes: 'Customer claimed they scanned correct QR; awaiting bank credit',
  },
  {
    id: 'TXN-9035',
    user_id: 1,
    utr_number: '628100112233',
    amount: 350.00,
    sender_vpa: 'sneha.verma@paytm',
    receiver_vpa: 'apex.retail@okhdfcbank',
    timestamp: '2026-10-07 10:20:00',
    verification_mode: 'manual',
    risk_score: 5,
    risk_level: 'LOW',
    verdict: 'VERIFIED GENUINE',
    status: 'verified',
    risk_factors: [
      { code: 'SYNTAX_OK', title: 'Julian Date 281 Verified', points: 0, severity: 'SAFE' },
    ],
    notes: 'Bakery counter',
  },
];

export const OCR_SAMPLE_RECEIPTS = [
  {
    id: 'sample_spoof_apk',
    name: '⚠️ Spoof APK Receipt (Fake PhonePe / Paytm App)',
    badge: 'HIGH FRAUD',
    isKnownSpoofDemo: true,
    amount: '₹3,500.00',
    utr: '9381029481',
    sender: 'spoof.bot@fakeupi',
    receiver: 'apex.retail@okhdfcbank',
    date: '2026-10-07 14:18',
    expectedScore: 85,
    color: '#ef4444',
    app: 'Fake Paytm Spoof APK v4.2',
    description: 'Generated by an illegal spoof APK simulator. Notice the 10-digit UTR instead of 12 digits and synthetic font glyphs.',
    artifacts: [
      'UTR has only 10 digits (Standard Indian UPI requires exactly 12)',
      'Julian day is missing from digits 2-4',
      'Rendered using unofficial Roboto Bold instead of PhonePe custom typeface',
      'Missing official NPCI transaction reference hash',
    ],
  },
  {
    id: 'sample_replay_attack',
    name: '🔄 Recycled Screenshot (Replay Attack)',
    badge: 'REPLAY ATTACK',
    amount: '₹1,450.00',
    utr: '628109482914',
    sender: 'rohit.kumar@okicici',
    receiver: 'apex.retail@okhdfcbank',
    date: '2026-10-07 15:32',
    expectedScore: 90,
    color: '#ef4444',
    app: 'Legitimate Google Pay (Replayed)',
    description: 'A genuine receipt from 45 minutes ago shown again by a fraudster hoping the cashier will only glance at the green tick.',
    artifacts: [
      'Identical UTR [628109482914] was already marked as redeemed 45 minutes ago',
      'Counterparty timestamp discrepancy detected',
      'Velocity alert: Duplicate checkout claim on single billing terminal',
    ],
  },
  {
    id: 'sample_genuine_receipt',
    name: '✅ Authentic Payment Receipt (Verified)',
    badge: 'VERIFIED SAFE',
    amount: '₹850.00',
    utr: '628190345678',
    sender: 'kavita.nair@okhdfcbank',
    receiver: 'apex.retail@okhdfcbank',
    date: '2026-10-07 15:48',
    expectedScore: 5,
    color: '#10b981',
    app: 'Google Pay for Business Official',
    description: '100% legitimate UPI transaction with correct 12-digit Julian encoding and matching merchant bank VPA.',
    artifacts: [
      'Valid 12-digit standard UTR structure',
      'Julian day matches today (Day 281)',
      'Zero duplicate collisions in merchant network',
      'Receiver VPA strictly matches registered terminal account',
    ],
  },
];
